name: parsing busschedule data
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
      - cron: "0 15 * * *"
 
jobs:
  run-parser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Bus Schedule Parser
        env:
          BUS_ID: ${{ secrets.BUS_ID }}
          BUS_PS: ${{ secrets.BUS_PS }}
        run: npx ts-node busschedule-parser.ts

      - name: Commit and Push Updates
        run: |
          git config --local user.email "ssb50800@gmail.com"
          git config --local user.name "Singhic"
          git add public/parser.json
          git commit -m "Fetch: Update busschedule data"
          git push
